### ISSUE TITLE
Check all Hive DDL commands

### ISSUE THREAD

**Issue by zsxwing** [delta-io/connectors#14]
Right now we have tested `CREATE TABLE`, `DROP TABLE`. But `ALTER TABLE` is missing. We should take a look at it and see what we can support and what we cannot.

**Comment by zsxwing** [comment]
Hive doesn't allow `ALTER TABLE` on a non-native table:
```
org.apache.hadoop.hive.ql.parse.SemanticException: ALTER TABLE cannot be used for a non-native table deltatbl
        at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.validateAlterTableType(DDLSemanticAnalyzer.java:1354)
        at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.addInputsOutputsAlterTable(DDLSemanticAnalyzer.java:1533)
        at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.addInputsOutputsAlterTable(DDLSemanticAnalyzer.java:1479)
        at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.analyzeAlterTableRenameCol(DDLSemanticAnalyzer.java:2661)
        at org.apache.hadoop.hive.ql.parse.DDLSemanticAnalyzer.analyzeInternal(DDLSemanticAnalyzer.java:283)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:258)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:512)
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1457)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
```

It's worth to investigate if we can bypass this check, or find a convenient way to update the table schema without re-creating the table.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
