### ISSUE TITLE
Get error with Spark and Hive when using this connector

### ISSUE THREAD

**Issue by DdMad** [delta-io/connectors#19]
Hi, I want to use Delta Lake together with Hive in Spark, but I got some "Operation not allowed: STORED BY" error. I checked this error but found nothing helpful. 

I wonder is it because this Hive connector is not supported when using Hive in Spark?

BTW, I tried running the create delta table SQL directly using hive CLI on the Hive machine, and it was working. 

Below is how I start the spark session:

```python
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .master('local')\
    .config("spark.databricks.delta.retentionDurationCheck.enabled", "false") \
    .config('spark.delta.logStore.class', 'org.apache.spark.sql.delta.storage.S3SingleDriverLogStore') \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .enableHiveSupport() \
    .getOrCreate()
```

I got error when I ran the code below:
```python
spark.sql("""
CREATE EXTERNAL TABLE deltaHiveTable (id BIGINT) 
STORED BY 'io.delta.hive.DeltaStorageHandler' 
LOCATION 's3a://my_bucket/my-delta-table/'
""")
```

```
Py4JJavaError: An error occurred while calling o69.sql.
: org.apache.spark.sql.catalyst.parser.ParseException: 
Operation not allowed: STORED BY(line 3, pos 0)

== SQL ==

CREATE EXTERNAL TABLE deltaHiveTable (id BIGINT) 
STORED BY 'io.delta.hive.DeltaStorageHandler' 
^^^
LOCATION 's3a://my_bucket/my-delta-table/'

	at org.apache.spark.sql.catalyst.parser.ParserUtils$.operationNotAllowed(ParserUtils.scala:41)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateFileFormat$1.apply(SparkSqlParser.scala:1251)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateFileFormat$1.apply(SparkSqlParser.scala:1243)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateFileFormat(SparkSqlParser.scala:1242)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateHiveTable$1$$anonfun$34.apply(SparkSqlParser.scala:1146)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateHiveTable$1$$anonfun$34.apply(SparkSqlParser.scala:1146)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateHiveTable$1.apply(SparkSqlParser.scala:1146)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateHiveTable$1.apply(SparkSqlParser.scala:1113)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateHiveTable(SparkSqlParser.scala:1113)
	at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateHiveTable(SparkSqlParser.scala:55)
	at org.apache.spark.sql.catalyst.parser.SqlBaseParser$CreateHiveTableContext.accept(SqlBaseParser.java:1215)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleStatement$1.apply(AstBuilder.scala:72)
	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleStatement$1.apply(AstBuilder.scala:72)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitSingleStatement(AstBuilder.scala:71)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parsePlan$1.apply(ParseDriver.scala:70)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parsePlan$1.apply(ParseDriver.scala:69)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:100)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:69)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zsxwing** [comment]
The connector cannot be used in Spark. The table creation command is a Hive command and needs to be run in Hive CLI. Delta's metastore support for Spark is still WIP. It will require Spark 3.0.

**Comment by zsxwing** [comment]
I'm closing this. This issue has been tracked in https://github.com/delta-io/delta/issues/85
