### ISSUE TITLE
GENERATE_GOLDEN_TABLES=1 build/sbt 'goldenTables/test' failure

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/connectors#209]
```===== FINISHED io.delta.golden.GoldenTables: 'deltalog-state-reconstruction-from-checkpoint-missing-protocol' =====

[info] - deltalog-state-reconstruction-from-checkpoint-missing-protocol *** FAILED ***
[info]   org.apache.spark.sql.AnalysisException: cannot resolve '`commitInfo`' given input columns: [add, cdc, metaData, protocol, remove, txn];
[info]   at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:143)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:140)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:333)
[info]   at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:333)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:330)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:399)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)

```
and 
```
===== FINISHED io.delta.golden.GoldenTables: 'deltalog-state-reconstruction-from-checkpoint-missing-metadata' =====

[info] - deltalog-state-reconstruction-from-checkpoint-missing-metadata *** FAILED ***
[info]   org.apache.spark.sql.AnalysisException: cannot resolve '`commitInfo`' given input columns: [add, cdc, metaData, protocol, remove, txn];
[info]   at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:143)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:140)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:333)
21/11/12 11:21:18 INFO GoldenTables: 

===== TEST OUTPUT FOR io.delta.golden.GoldenTables: 'deltalog-invalid-protocol-version' =====

[info]   at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:333)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:330)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:399)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)
```

**Comment by kination** [comment]
@allisonport-db @zsxwing is this still remaining issue?

**Comment by allisonport-db** [comment]
yes if you run the command in the title you will see the above error
