### ISSUE TITLE
Presto doesn't recognise Hive-External table for Delta: com.facebook.presto.spi.PrestoException: InputFormat is not present in StorageFormat

### ISSUE THREAD

**Issue by amarsladdha** [delta-io/connectors#28]
Hello,

I am seeing following exception when I used this connector with presto. Can you please help me with this issue.

### A) My server setup:
1. Spark 2.4.4
2. Hadoop 3.2.1
3. Hive 2.3.6
4. Scala 2.11.12
5. Presto 0.228

### B) Build changes:
I had to change the change some build options in order create connector jars for my cluster

```
-val sparkVersion = "2.4.3"
-val hadoopVersion = "2.7.2"
-val hiveVersion = "2.3.3"
+val sparkVersion = "2.4.4"
+val hadoopVersion = "3.2.1"
+val hiveVersion = "2.3.6"
 val deltaVersion = "0.5.0"
 
 lazy val commonSettings = Seq(
@@ -53,8 +53,8 @@ lazy val core = (project in file("core"))
     name := "delta-core-shaded",
     libraryDependencies ++= Seq(
       "io.delta" %% "delta-core" % deltaVersion excludeAll ExclusionRule("org.apache.hadoop"),
-      "org.apache.spark" %% "spark-sql" % sparkVersion excludeAll ExclusionRule("org.apache.hadoop"),
-      "org.apache.hadoop" % "hadoop-client" % hadoopVersion % "provided"
+      "org.apache.spark" %% "spark-sql" % sparkVersion excludeAll ExclusionRule("org.apache.hadoop") exclude("org.glassfish.hk2", "hk2-utils") exclude("org.glassfish.hk2", "hk2-locator") exclude("javax.validation", "validation-api"),
+      "org.apache.hadoop" % "hadoop-client" % hadoopVersion % "provided" excludeAll ExclusionRule("org.slf4j", "slf4j-log4j12")
     ),

```

### C) Exception:

```
com.facebook.presto.spi.PrestoException: InputFormat is not present in StorageFormat
	at com.facebook.presto.hive.metastore.StorageFormat.getInputFormat(StorageFormat.java:57)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:291)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:264)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:96)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:193)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Thanks,
Amar

**Comment by zsxwing** [comment]
Unfortunately, this connector doesn't work in Presto. It doesn't support Hive's StorageHandler interface which we implement to make it work with Hive.

**Comment by amarsladdha** [comment]
Hi @zsxwing ,

Thank you for clarifying. 

Presto documentation says that it can support custom storage handlers but we need to manually add the handler jars to all nodes. Do you think if these steps will work for Delta-Hive storage handler? 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/4811706/76478538-39a4d680-63c6-11ea-8651-dced133fe728.png">

In any case, will you be supporting Delta-Presto connector?

Thanks,
Amar

**Comment by zsxwing** [comment]
I didn’t know this. Could you try it if you have the environment ready and report back, please? We don’t have plans for Presto right now. It would be great that the delta storage handler works in Presto as well.

**Comment by Emanueldamianpaz** [comment]
Hello, are there plans to develop the Delta-presto connector soon?

**Comment by dennyglee** [comment]
As noted,  with the linked PR #82 - this is being worked on in addition to the current manifest method.

**Comment by zsxwing** [comment]
Closing this. It's expected that the existing Hive connector doesn't work with Presto. We are building a native Presto connector.
