### ISSUE TITLE
Standalone to access Azure ADLS2 file system with wrong account name will cause infinite loop

### ISSUE THREAD

**Issue by zhudaxi** [delta-io/connectors#339]
We are using delta-standalone_2.12 version 0.4.0 to access Azure ADLS2 delta folder.
Azure ADLS2 has storage account (let's say with a name `my_storage_account`), and generate an access key (let's say the key is `my_key_string`), and a container is created under this storage account (let's say the container name is `my_container`).
The following code will cause infinite loop when create DeltaLog against file in this ADLS2 storage. 
The storage account name was wrongly input as `wrong_stroage_account` in the code.
```
Configuration hadoopConfig = new Configuration(); 
hadoopConfig.set("fs.azure.account.key.wrong_stroage_account.dfs.core.windows.net","my_key_string");
DeltaLog log = DeltaLog.forTable(hadoopConfig,"abfss://my_container@wrong_stroage_account.dfs.core.windows.net/delta-table/");
```
It seems to be the retry logic mistake. 

Below is the dependencies we have for this case:
```
<dependencies>
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-standalone_2.12</artifactId>
            <version>0.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-hadoop</artifactId>
            <version>1.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-azure</artifactId>
            <version>3.3.1</version>
        </dependency>
    </dependencies>
```

**Comment by allisonport-db** [comment]
Hi @zhudaxi thanks for reporting this. We will take a look.

**Comment by allisonport-db** [comment]
@zhudaxi Can you provide the stack trace when you kill the process?

**Comment by tdas** [comment]
Alternatively, since its a java process. You can use `jstack` command to get the thread dump of the process. Taking repeated thread dump can help identify where it is stuck in this seeming retry loop.

**Comment by zhudaxi** [comment]
Here it is:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.executeHttpOperation(AbfsRestOperation.java:287)
	  at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.completeExecute(AbfsRestOperation.java:205)
	  at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.lambda$execute$0(AbfsRestOperation.java:181)
	  at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation$$Lambda$91.230526532.apply(Unknown Source:-1)
	  at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:454)
	  at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:179)
	  at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getPathStatus(AbfsClient.java:733)
	  at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.openFileForRead(AzureBlobFileSystemStore.java:664)
	  at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.open(AzureBlobFileSystem.java:197)
	  at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.open(AzureBlobFileSystem.java:188)
	  at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
	  at io.delta.standalone.internal.storage.HadoopFileSystemLogStore.read(HadoopFileSystemLogStore.scala:41)
	  at io.delta.standalone.internal.Checkpoints.loadMetadataFromFile(Checkpoints.scala:137)
	  at io.delta.standalone.internal.Checkpoints.lastCheckpoint(Checkpoints.scala:111)
	  at io.delta.standalone.internal.Checkpoints.lastCheckpoint$(Checkpoints.scala:110)
	  at io.delta.standalone.internal.DeltaLogImpl.lastCheckpoint(DeltaLogImpl.scala:41)
	  at io.delta.standalone.internal.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:218)
	  at io.delta.standalone.internal.SnapshotManagement.$init$(SnapshotManagement.scala:37)
	  at io.delta.standalone.internal.DeltaLogImpl.<init>(DeltaLogImpl.scala:46)
	  at io.delta.standalone.internal.DeltaLogImpl$.apply(DeltaLogImpl.scala:225)
	  at io.delta.standalone.internal.DeltaLogImpl$.forTable(DeltaLogImpl.scala:203)
	  at io.delta.standalone.internal.DeltaLogImpl.forTable(DeltaLogImpl.scala:-1)
	  at io.delta.standalone.DeltaLog.forTable(DeltaLog.java:124)
```

**Comment by zhudaxi** [comment]
The `retryCount` keeps increasing in `executeHttpOperation` in AbfsRestOperation.java

**Comment by allisonport-db** [comment]
It seems this the same problem summarized [here](https://docs.microsoft.com/en-us/azure/databricks/kb/data-sources/abfs-client-hang). Since this is an issue with abfs we can't help much.

To confirm, you are able to create the `DeltaLog` with the correct account id?

**Comment by zhudaxi** [comment]
With correct account id we can create DeltaLog.
Thanks.

**Comment by allisonport-db** [comment]
Awesome, closing this issue since it's outside our code base.

**Comment by zhudaxi** [comment]
@allisonport-db We found this config item `fs.azure.io.retry.max.retries ` in hadoop config can control the retry attempt in hadoop azure. Default is 30, but if we set it to a small number, this "hanging" problem can be solved. Just FYI.

**Comment by allisonport-db** [comment]
Awesome, thanks for updating this.
