### ISSUE TITLE
Missing dependency when trying to store Timestamp

### ISSUE THREAD

**Issue by Xoerk** [delta-io/connectors#351]
Getting the following exception when tried to store timestamp in parquet:

`12:08:21.364 [flink-akka.actor.default-dispatcher-67] INFO  o.a.f.r.e.ExecutionGraph - KeyedProcess -> DeltaPacketDataAssignTimestampAndWatermarks -> Map -> Sink PacketToDataBricks (2/2) (58df0a1b3b8b4b0e2ccce628b1a55b08) switched from RUNNING to FAILED on d3da4105-ee3a-4c0c-b5c3-707202649d56 @ localhost (dataPort=-1).
java.lang.NoClassDefFoundError: org/apache/flink/table/data/vector/Dictionary
	at org.apache.flink.formats.parquet.row.ParquetRowDataWriter.timestampToInt96(ParquetRowDataWriter.java:234)
	at org.apache.flink.formats.parquet.row.ParquetRowDataWriter.access$1100(ParquetRowDataWriter.java:48)
	at org.apache.flink.formats.parquet.row.ParquetRowDataWriter$TimestampWriter.write(ParquetRowDataWriter.java:225)
	at org.apache.flink.formats.parquet.row.ParquetRowDataWriter.write(ParquetRowDataWriter.java:84)
	at org.apache.flink.formats.parquet.row.ParquetRowDataBuilder$ParquetWriteSupport.write(ParquetRowDataBuilder.java:88)
	at org.apache.flink.formats.parquet.row.ParquetRowDataBuilder$ParquetWriteSupport.write(ParquetRowDataBuilder.java:70)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
	at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
	at org.apache.flink.formats.parquet.ParquetBulkWriter.addElement(ParquetBulkWriter.java:52)
	at org.apache.flink.streaming.api.functions.sink.filesystem.DeltaBulkPartWriter.write(DeltaBulkPartWriter.java:93)
	at io.delta.flink.sink.internal.writer.DeltaWriterBucket.write(DeltaWriterBucket.java:334)
	at io.delta.flink.sink.internal.writer.DeltaWriter.write(DeltaWriter.java:259)
	at org.apache.flink.streaming.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:163)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.runtime.operators.TimestampsAndWatermarksOperator.processElement(TimestampsAndWatermarksOperator.java:103)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
	at testing.io.delta.PacketConvertToRowData.processElement(PacketRowConvert.scala:37)
	at testing.io.delta.PacketConvertToRowData.processElement(PacketRowConvert.scala:24)
	at org.apache.flink.streaming.api.operators.KeyedProcessOperator.processElement(KeyedProcessOperator.java:83)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:233)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
	at java.lang.Thread.run(Thread.java:748)`

Scala: 2.12.12
flink: 1.14.4

After some investigation, it seems that we should also include '**flink-table-runtime**' in the dependency

**Comment by scottsand-db** [comment]
Hi @Xoerk - thanks for making this issue. Can you share with me your original `pom.xml` you were using? And then the latest `pom.xml` you have that fixed your issue?

Was it the same one as is suggested in the flink README? https://github.com/delta-io/connectors/tree/master/flink

**Comment by scottsand-db** [comment]
cc @pkubit-g

**Comment by Xoerk** [comment]
Hi,
I deep-dived into the problem and noticed that there is no '[flink-table-runtime-blink](https://mvnrepository.com/artifact/org.apache.flink/flink-table-runtime-blink)' for Flink 1.14.x.
This is why I had to add [flink-table-runtime](https://mvnrepository.com/artifact/org.apache.flink/flink-table-runtime) as a dependency. 

So I guess we can close this issue.
