### ISSUE TITLE
when support spark3.0

### ISSUE THREAD

**Issue by chongchuanbing** [delta-io/connectors#38]
spark 3.0.0-rc1
delta 0.5.0

```
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.classForName(Ljava/lang/String;)Ljava/lang/Class;
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
  at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
  at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
  at org.apache.spark.sql.delta.DeltaLog$.apply(DeltaLog.scala:740)
  at org.apache.spark.sql.delta.DeltaLog$.forTable(DeltaLog.scala:712)
  at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:169)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
  ... 47 elided
Caused by: java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.classForName(Ljava/lang/String;)Ljava/lang/Class;
  at org.apache.spark.sql.delta.storage.LogStoreProvider.createLogStore(LogStore.scala:122)
  at org.apache.spark.sql.delta.storage.LogStoreProvider.createLogStore$(LogStore.scala:120)
  at org.apache.spark.sql.delta.DeltaLog.createLogStore(DeltaLog.scala:58)
  at org.apache.spark.sql.delta.storage.LogStoreProvider.createLogStore(LogStore.scala:117)
  at org.apache.spark.sql.delta.storage.LogStoreProvider.createLogStore$(LogStore.scala:115)
  at org.apache.spark.sql.delta.DeltaLog.createLogStore(DeltaLog.scala:58)
  at org.apache.spark.sql.delta.DeltaLog.<init>(DeltaLog.scala:79)
  at org.apache.spark.sql.delta.DeltaLog$$anon$3.$anonfun$call$2(DeltaLog.scala:744)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
  at org.apache.spark.sql.delta.DeltaLog$$anon$3.$anonfun$call$1(DeltaLog.scala:744)
  at com.databricks.spark.util.DatabricksLogging.recordOperation(DatabricksLogging.scala:77)
  at com.databricks.spark.util.DatabricksLogging.recordOperation$(DatabricksLogging.scala:67)
  at org.apache.spark.sql.delta.DeltaLog$.recordOperation(DeltaLog.scala:671)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:103)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:89)
  at org.apache.spark.sql.delta.DeltaLog$.recordDeltaOperation(DeltaLog.scala:671)
  at org.apache.spark.sql.delta.DeltaLog$$anon$3.call(DeltaLog.scala:743)
  at org.apache.spark.sql.delta.DeltaLog$$anon$3.call(DeltaLog.scala:740)
  at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
  ... 58 more
```

**Comment by zsxwing** [comment]
This connector cannot be used in Spark. See https://github.com/delta-io/connectors/blob/v0.1.0/README.md#can-i-use-this-connector-in-apache-spark-or-presto

**Comment by zsxwing** [comment]
If you are looking for how to read Delta tables in Spark 3.0.0, [Delta Lake 0.7.0](https://github.com/delta-io/delta/releases/tag/v0.7.0) has been released. You can use it in Spark 3.0.0.
