### ISSUE TITLE
Delta Standalone: Stat serialization/deserialization inconsistent

### ISSUE THREAD

**Issue by gopik** [delta-io/connectors#380]
stats is a string field in AddFile. But while serializing it to the delta log, it's interpreted as json and serialized as object instead of string. But while deserialization, it fails since it expects the field to have a string value and not an object.

example log file where deserialization fails:
```
{"commitInfo":{"timestamp":1655866112885,"operation":"STREAMING UPDATE","operationParameters":{"mode":"Append","partitionBy":"[]"},"isolationLevel":"Serializable","isBlindAppend":true,"operationMetrics":{"numOutputRows":"6","numAddedFiles":"1","numOutputBytes":"630","numRemovedFiles":"0"},"engineInfo":"flink-engine/1.13.0-flink-delta-connector/0.5.0-SNAPSHOT Delta-Standalone/0.4.1"}}
{"protocol":{"minReaderVersion":1,"minWriterVersion":2}}
{"metaData":{"id":"907d4e40-cd99-455c-9508-22cd88e8f84f","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"f2\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"f3\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}]}","partitionColumns":[],"configuration":{},"createdTime":1655866112681}}
{"txn":{"appId":"358a08c6-61c6-4b0e-9119-8bab6dc40f6e","version":1,"lastUpdated":1655866112832}}
{"add":{"path":"part-d15689cd-24a0-463a-bdf8-d23948c5140b-0.snappy.parquet","partitionValues":{},"size":630,"modificationTime":1655866110161,"dataChange":true,"stats":{"numRecords":6,"minValues":{"f1":"Mg==","f2":"MTY=","f3":1},"maxValues":{"f1":"OQ==","f2":"ODE=","f3":19},"nullCounts":{"f1":0,"f2":0,"f3":0}}}}
```

Exception stack trace:
```
[Sink Global Committer: Unnamed (1/1)#0] WARN org.apache.flink.runtime.taskmanager.Task - Sink Global Committer: Unnamed (1/1)#0 (ef8d2538dd6a4f9d59fbf83afa5866c2) switched from RUNNING to FAILED with failure cause: shadedelta.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"add":{"path":"part-d15689cd-24a0-463a-bdf8-d23948c5140b-0.snappy.parquet","partitionValues":{},"size":630,"modificationTime":1655866110161,"dataChange":true,"stats":{"numRecords":6,"minValues":{"f1":"Mg==","f2":"MTY=","f3":1},"maxValues":{"f1":"OQ==","f2":"ODE=","f3":19},"nullCounts":{"f1":0,"f2":0,"f3":0}}}}"; line: 1, column: 168] (through reference chain: io.delta.standalone.internal.actions.SingleAction["add"]->io.delta.standalone.internal.actions.AddFile["stats"])
        at shadedelta.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at shadedelta.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
        at shadedelta.com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
        at shadedelta.com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
        at shadedelta.com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
        at shadedelta.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
        at shadedelta.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at shadedelta.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at shadedelta.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at shadedelta.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at shadedelta.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at shadedelta.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at shadedelta.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
        at shadedelta.com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:206)
        at shadedelta.com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:205)
        at io.delta.standalone.internal.util.JsonUtils$$anon$1.readValue(JsonUtils.scala:33)
        at io.delta.standalone.internal.SnapshotImpl.$anonfun$loadInMemory$4(SnapshotImpl.scala:177)
```

**Comment by gopik** [comment]
This works ok if added json is escaped. 

Instead of
```
{"add":{"path":"part-d15689cd-24a0-463a-bdf8-d23948c5140b-0.snappy.parquet","partitionValues":{},"size":630,"modificationTime":1655866110161,"dataChange":true,"stats":{"numRecords":6,"minValues":{"f1":"Mg==","f2":"MTY=","f3":1},"maxValues":{"f1":"OQ==","f2":"ODE=","f3":19},"nullCounts":{"f1":0,"f2":0,"f3":0}}}
```

following works
```
{"add":{"path":"part-2fffa131-f3f3-4344-b328-c0f46c19eea7-0.snappy.parquet","partitionValues":{},"size":589,"modificationTime":1655872501801,"dataChange":true,"stats":"{\"numRecords\":3,\"minValues\":{\"f1\":\"Mw==\",\"f2\":\"MTk=\",\"f3\":3},\"maxValues\":{\"f1\":\"Nw==\",\"f2\":\"NTM=\",\"f3\":11},\"nullCounts\":{\"f1\":0,\"f2\":0,\"f3\":0}}"}
```

**Comment by scottsand-db** [comment]
Hi @gopik - thanks for this issue. I'll take a look.

**Comment by scottsand-db** [comment]
Hi @gopik - sorry for the delay. I've confirmed this issue myself, too.

Want to copy over https://github.com/delta-io/delta/blob/master/core/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala from delta-io/delta repository?

And perhaps investigate the fix?

**Comment by gopik** [comment]
Sure, I'll look into this.

**Comment by scottsand-db** [comment]
Thanks!

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
