### ISSUE TITLE
CREATE EXTERNAL TABLE fails with java.lang.IllegalArgumentException: System memory 242745344 must be at least 471859200

### ISSUE THREAD

**Issue by langelgjm** [delta-io/connectors#46]
I try to create an external table using sample delta data (converted from regular parquet files here: https://github.com/Teradata/kylo/tree/master/samples/sample-data/parquet):

```
CREATE EXTERNAL TABLE `default.userdata_delta` (
    `registration_dttm`timestamp,
    `id` int,
    `first_name` string,
    `last_name` string,
    `email` string,
    `gender` string,
    `ip_address` string,
    `cc` string,
    `country` string,
    `birthdate` string,
    `salary` double,
    `title` string,
    `comments` string
)
STORED BY 'io.delta.hive.DeltaStorageHandler'  
LOCATION
  's3a://...'
```

I receive the following error:

```
java.lang.IllegalArgumentException: System memory 242745344 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
```

Traceback:

```
2020-08-28 12:57:13,548 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] ql.Driver: Starting task [Stage-0:DDL] in serial mode
2020-08-28 12:57:13,550 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] plan.CreateTableDesc: Use StorageHandler-supplied org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe for table userdata_delta
2020-08-28 12:57:13,553 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] exec.DDLTask: creating table default.userdata_delta on s3a://dataeng-data-test/dev/coredata/eval/kylin/userdata_delta
2020-08-28 12:57:14,024 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SparkContext: Running Spark version 2.4.3
2020-08-28 12:57:14,054 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SparkContext: Submitted application: Delta Connector
2020-08-28 12:57:14,119 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SecurityManager: Changing view acls to: root
2020-08-28 12:57:14,120 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SecurityManager: Changing modify acls to: root
2020-08-28 12:57:14,120 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SecurityManager: Changing view acls groups to: 
2020-08-28 12:57:14,121 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SecurityManager: Changing modify acls groups to: 
2020-08-28 12:57:14,122 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2020-08-28 12:57:14,413 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] util.Utils: Successfully started service 'sparkDriver' on port 36643.
2020-08-28 12:57:14,439 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SparkEnv: Registering MapOutputTracker
2020-08-28 12:57:14,451 ERROR [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: System memory 242745344 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
	at org.apache.spark.memory.UnifiedMemoryManager$.getMaxMemory(UnifiedMemoryManager.scala:219)
	at org.apache.spark.memory.UnifiedMemoryManager$.apply(UnifiedMemoryManager.scala:199)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:330)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:185)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:424)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:935)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at org.apache.spark.sql.delta.DeltaHelper$.spark(DeltaHelper.scala:348)
	at org.apache.spark.sql.delta.DeltaHelper$.loadDeltaLatestSnapshot(DeltaHelper.scala:178)
	at io.delta.hive.DeltaStorageHandler.preCreateTable(DeltaStorageHandler.scala:189)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:747)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:740)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
	at com.sun.proxy.$Proxy36.createTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:852)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:867)
	at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:4356)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:354)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:233)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:184)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:403)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:821)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:759)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:686)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
2020-08-28 12:57:14,465 INFO  [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] spark.SparkContext: Successfully stopped SparkContext
2020-08-28 12:57:14,475 ERROR [fcf5ca99-91dd-47a8-b2e7-c37fb5e239b4 main] exec.DDLTask: SparkSession.scala:926)
	at org.apache.spark.sql.delta.DeltaHelper$.spark(DeltaHelper.scala:348)
	at org.apache.spark.sql.delta.DeltaHelper$.loadDeltaLatestSnapshot(DeltaHelper.scala:178)
	at io.delta.hive.DeltaStorageHandler.preCreateTable(DeltaStorageHandler.scala:189)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:747)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:740)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
	at com.sun.proxy.$Proxy36.createTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:852)
	... 22 more

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.IllegalArgumentException: System memory 242745344 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
```

Since the Hive connector uses its own local Spark, I cannot configure this setting through the normal means (spark-defaults.conf). Also it turns out the error message is misleading - the value that needs to be adjusted is not `spark.driver.memory`, it is `spark.testing.memory`.

I added `.config("spark.testing.memory", 536870912)` after line 348 here: https://github.com/delta-io/connectors/blob/master/hive/src/main/scala/org/apache/spark/sql/delta/DeltaHelper.scala#L348

Then I rebuilt the JARs and now I am able to create the external table as expected.

This link was helpful: https://www.waitingforcode.com/apache-spark/troubleshooting-system-memory-must-be-at-least-error/read

And here is the relevant code in `org.apache.spark.memory.UnifiedMemoryManeger.getMaxMemory`: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/memory/UnifiedMemoryManager.scala#L214

**Comment by zsxwing** [comment]
`spark.testing.memory` is a config to allow we running tests in a low heap JVM. It's not a config that should be used in production codes.

What's the heap size in your hive client? Generally, Spark requires at least 1GB heap.

**Comment by langelgjm** [comment]
You're right, it looks like we just had the default Hive shell heap size of 256 MB. Placing `export HADOOP_HEAPSIZE=1024` in `hive-env.sh` fixed this issue. We can now create the external table using the JARs compiled with no changes.
