### ISSUE TITLE
Hive SQL counts queries are not working on Hive tables created on Delta format

### ISSUE THREAD

**Issue by abhilater** [delta-io/connectors#84]
Hive external tables created on Delta format paths are working for simple select queries but not for aggregated count queries.

### Steps to reproduce

1. Added delta-hive assembly jar to classpath using following approach
```
<property>
          <name>hive.aux.jars.path</name>
          <value>s3://helpshift-test-bucket/emrpoc/workspace/abhishekgupta/delta-hive-assembly_2.11-0.2.0.jar</value>
  </property>
```

2. Restarted Hive server
sudo systemctl stop hive-server2.service
sudo systemctl start hive-server2.service

### On Hive CLI

3. hive
```
SET hive.input.format=io.delta.hive.HiveInputFormat;
SET hive.tez.input.format=io.delta.hive.HiveInputFormat;
SET hive.execution.engine=tez;
```

4. Create Ext Table

```
CREATE EXTERNAL TABLE deltaTable(domain string, app_id string, app_name string, platform_id string, event_date date)
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION 's3://helpshift-test-bucket/emrpoc/sinks/sdk_events_test_delta1';
```

```
select * from deltatable;
>> results show up
```
```
select count(*) from deltatable;
>> Error - java.lang.ClassNotFoundException: Class io.delta.hive.HiveInputFormat not found
```

Stack trace
=========
```Vertex killed, vertexName=Reducer 2, vertexId=vertex_1617974054397_0025_1_01, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1617974054397_0025_1_01 [Reducer 2] killed/failed due to:OTHER_VERTEX_FAILURE]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:1
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask. Vertex failed, vertexName=Map 1, vertexId=vertex_1617974054397_0025_1_00, diagnostics=[Vertex vertex_1617974054397_0025_1_00 [Map 1] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: deltatable initializer failed, vertex=vertex_1617974054397_0025_1_00 [Map 1], org.apache.tez.dag.api.TezUncheckedException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.delta.hive.HiveInputFormat not found
        at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateOldSplits(MRInputHelpers.java:472)
        at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateInputSplitsToMem(MRInputHelpers.java:337)
        at org.apache.tez.mapreduce.common.MRInputAMSplitGenerator.initialize(MRInputAMSplitGenerator.java:122)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:278)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:269)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1926)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:269)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:253)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.delta.hive.HiveInputFormat not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2460)
        at org.apache.hadoop.mapred.JobConf.getInputFormat(JobConf.java:707)
        at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateOldSplits(MRInputHelpers.java:470)
        ... 13 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.delta.hive.HiveInputFormat not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2428)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2452)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: Class io.delta.hive.HiveInputFormat not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2332)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2426)
        ... 16 more
```

**Comment by zsxwing** [comment]
This sounds a Hive specific issue. I'm not familiar with how `hive.aux.jars.path` works internally. Maybe ask this in hive mailing list?

**Comment by abhilater** [comment]
I am also guessing the same, will check in the Hive mailing list on what is the right way to add a permanent JAR on Hive's classpath. The Delta Hive Connector documentation just mentions updating `hive.aux.jars.path` on the node where we are running Hive client, but it is clear that it is not enough for aggregate queries that runs on TEZ/YARN.

**Comment by zsxwing** [comment]
Cool. It would be great if you can help us improve the doc after you get the answer from the Hive community.

**Comment by abhilater** [comment]
@zsxwing  We were able to get this working using the Hive CLI `ADD JAR` command.

**Comment by dennyglee** [comment]
Thanks, @abhilater - as you noted, we'll close this issue.
