### ISSUE TITLE
Hive 3+ support

### ISSUE THREAD

**Issue by dharshanshastry** [delta-io/connectors#86]
The Latest Hive connector release is compatible with Hive 2+ releasees.  Any idea when can we expect Hive 3+ support ? 

Trying with Hive 3.0 ends up with below exception as "MetaStoreUtils is moved to utils package in Hive 3"

`java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/MetaStoreUtils
	at io.delta.hive.DeltaStorageHandler.preCreateTable(DeltaStorageHandler.scala:173) ~[delta-hive-assembly_2.12-0.2.0.jar:0.2.0]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:832) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:822) ~[hive-exec-3.1.2.jar:3.1.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]`

**Comment by dennyglee** [comment]
We do not have a current timeline for this though it is a good idea.

**Comment by dharshanshastry** [comment]
Thank you 👍

**Comment by zsxwing** [comment]
Closing this. We will use the existing issue #36 to track Hive 3 support.
