### ISSUE TITLE
Illegal Access Error while querying  the created hive table through deltalake connector

### ISSUE THREAD

**Issue by bkumaran08** [delta-io/connectors#96]
Hive version :  2.6
delta lake connector version : delta-hive-assembly_2.11-0.2.0.jar
Spark version : 3.1.1
Scala version :2.12
delta-core : 1.0.0

I have created a deltalake table using spark, and then I am able to create a hive table out of it using delta lake connector.

When we tried to access the created table in hive, it is throwing below error.

Delta lake table is working fine when I query it through spark.

**Error Trace** 

Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.apache.hadoop.hive.ql.io.parquet.read.DataWritableReadSupport.getColumnNames(Ljava/lang/String;)Ljava/util/List; from class io.delta.hive.DeltaStorageHandler
        at io.delta.hive.DeltaStorageHandler.configureInputJobProperties(DeltaStorageHandler.scala:71)
        at org.apache.hadoop.hive.ql.plan.PlanUtils.configureJobPropertiesForStorageHandler(PlanUtils.java:820)
        at org.apache.hadoop.hive.ql.plan.PlanUtils.configureInputJobPropertiesForStorageHandler(PlanUtils.java:790)
        at org.apache.hadoop.hive.ql.optimizer.SimpleFetchOptimizer$FetchData.convertToWork(SimpleFetchOptimizer.java:385)
        at org.apache.hadoop.hive.ql.optimizer.SimpleFetchOptimizer$FetchData.access$000(SimpleFetchOptimizer.java:323)
        at org.apache.hadoop.hive.ql.optimizer.SimpleFetchOptimizer.optimize(SimpleFetchOptimizer.java:134)
        at org.apache.hadoop.hive.ql.optimizer.SimpleFetchOptimizer.transform(SimpleFetchOptimizer.java:105)
        at org.apache.hadoop.hive.ql.optimizer.Optimizer.optimize(Optimizer.java:215)
        at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:10572)
        at org.apache.hadoop.hive.ql.parse.CalcitePlanner.analyzeInternal(CalcitePlanner.java:219)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:238)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:474)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:330)
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1233)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1274)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1170)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1160)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:217)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:169)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:380)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:740)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:685)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:625)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:233)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)

**Comment by zsxwing** [comment]
Please check this [FAQ](https://github.com/delta-io/connectors#if-i-create-a-table-using-the-connector-in-hive-can-i-query-it-in-apache-spark-or-presto)

> If I create a table using the connector in Hive, can I query it in Apache Spark or Presto?
> No. The table created by this connector in Hive cannot be read in any other systems right now. We recommend to create different tables in different systems but point to the same path. Although you need to use different table names to query the same Delta table, the underlying data will be shared by all of systems.

**Comment by zsxwing** [comment]
NVM. I misread your question.

I found the method we used required Hive 2.3: https://github.com/apache/hive/blob/rel/release-2.3.0/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java#L73

It's private before Hive 2.3.0. Thanks for reporting this. 

> Hive version : 2.6

Is it a typo since Hive doesn't have any 2.6.x version. Could you try to upgrade the Hive version?

**Comment by zsxwing** [comment]
Fixed by #198
